### ISSUE TITLE
New feature: Internal evaluation module

### ISSUE THREAD

**Issue by NilHomedes** [AjuntamentdeBarcelona/internal-evaluation-module#2]
**Is your feature request related to a problem? Please describe**
When a proposal is being reviewed by a group of evaluators, the current interface is not usable to discuss and make a collective decision on the answer of a proposal. 

In that sense, it’s important to have the possibility to add an internal evaluation attached to a text to expone your assessment.

**Describe the solution you'd like**
As an evaluator, I want to have a new feature that allows me to see clearly the evaluation made by others and to discuss collectively the answer to a proposal. This feature must comply with the following characteristics:

- As an evaluator, I want to add an internal evaluation so the other evaluators can read my assessment and see my status for that proposal. There will be as many internal evaluations as assigned evaluators. 
- The internal evaluation should be composed of: An status + a text field. (As it works with proposal answers).
- As an evaluator, I can choose between the status options defined to answer proposals.
- Evaluators will have a maximum of one internal evaluation per each evaluator.
- The internal evaluation will be editable. The last update date should be shown.
- It will be mandatory to define a private status when publishing your evaluation.
- This will be a new space in the proposal admin page called “Internal evaluation”.

**Glossary**
**Internal evaluation status:** This is the assessment made by the evaluator based on the proposal answer statuses, and is linked to a text field. This is not public. It is only for evaluators purposes. This is editable.
**Internal evaluation:** This is a field composed by the internal status + a text field to justify your assessment. This will be editable but does not allow replies. This is what will be taken into account to define whether an evaluator has evaluated a proposal or not.
**Answers:** This is the public answer to a proposal. 
**Private notes**: These are the comment space that evaluators use to discuss the answer to a proposal. This is not public. It is only for valuators purposes.

**Mockups**
(needed)

**Does this issue could impact on users private data?**
No

**Acceptance Criteria:**
- [x] Given that a I’m an evaluator
When I go to a proposal manager page
Then I can see a new field called "Internal evaluation" after the "Private notes" field.
- [x] Given that a I’m an evaluator
When I want to add an internal evaluation to a proposal
Then I can write on a text field and choose a status between the options available.
- [x] Given that I’m an evaluator
When I want to edit my internal evaluation
Then I can edit the status and the text
- [x] Given that I’m an evaluator
When I want to read the others internal evaluations
Then I can see clearly the others internal evaluations with the evaluator’s name, the last update date and time, and the private status of each one.
- [x] Given that I’m and administrator or an evaluator
When I want to see the internal evaluation progress of a proposal
Then I can see how many evaluations are missing, on the assigned ones
- [x] Given that I’m an evaluator
When an admin add a new status to a proposal component 
Then I can select the new status in the internal evaluation field

**Comment by furilo** [comment]
What are the statuses? Are they fixed?

**Comment by furilo** [comment]
cc @NilHomedes

**Comment by NilHomedes** [comment]
> What are the statuses? Are they fixed?

I'm referring to proposal answer statuses: https://decidim-lot2.populate.tools/admin/participatory_processes/branch-highway/components/4/manage/proposal_states
After this PR https://github.com/decidim/decidim/pull/12052 , admins can define different proposal statuses to answer proposals.

**Comment by furilo** [comment]
Ok, it was not clear to me that they were the same.

**Comment by furilo** [comment]
Hi @NilHomedes

This is a first exploration of how this screen could look like:

1. Collapsible box for Evaluations as we have for Private notes
2. List of evaluations. I've combined date (last updated) and evaluator name in 1 column because we don't have enough space for one column for each
3. Column for status + the text of the evaluation
4. Notice of how many evaluations are done, how many pending (ie. 3 out 4)
5. Action: you'd only be able to edit yours

<img width="1435" alt="57741" src="https://github.com/AjuntamentdeBarcelona/decidim-internal-evaluation-module/assets/24740/616e4661-caf1-4f3a-8d18-6b9a3c879bf3">

To decide: one a evaluator clicks on edit she will see the textarea. 
- We can open it inline in the table (everything would be a little bit tight, and implementation might get tricky)
- or open a new page to perform this action 

What do you prefer? 

Anything I'm missing?

**Comment by furilo** [comment]
(@NilHomedes please share with the rest of Product if needed, as I can't mention them from this repo)

**Comment by furilo** [comment]
@NilHomedes any feedback on this? Can we start? We are currently waiting for the OK as, as we spoke, this should be done first.

**Comment by NilHomedes** [comment]
Hi @furilo 
We have been discussing this yesterday with Barcelona Team, some comments:

> To decide: one a evaluator clicks on edit she will see the textarea.

We think the best approach here could be to open a pop-up with the text field and the status selector. So the valuator has to write their assessment and select a status. If an evaluator want to edit their internal evaluation, they can click on the edit icon and edit it from the pop-up. 

**Order of the sections**
We want to have the "Private notes" section above the "Internal evaluations" section.
The "Internal evaluations" section should be displayed by default. So the evaluators can easily see where they have to put their input.

**Comment by furilo** [comment]
> We think the best approach here could be to open a pop-up with the text field and the status selector. So the valuator has to write their assessment and select a status. If an evaluator want to edit their internal evaluation, they can click on the edit icon and edit it from the pop-up.

OK

> We want to have the "Private notes" section above the "Internal evaluations" section.

OK

> The "Internal evaluations" section should be displayed by default. So the evaluators can easily see where they have to put their input.

What do you mean? That it's always open when you into a proposal? It's the current behaviour, if I'm not wrong.

**Comment by NilHomedes** [comment]
> What do you mean? That it's always open when you into a proposal? It's the current behaviour, if I'm not wrong.

I mean that it would be open always be default. 
So, when an evaluator go into a proposal, they should see the "Internal Evaluation" field open:
![image](https://github.com/AjuntamentdeBarcelona/decidim-internal-evaluation-module/assets/71442847/f2a3d8a9-3c5d-44f3-b027-a6bb05cfa020)
I was saying that to differentiate the behaviour of "Internal evaluation" from "Private notes", which are collpased by default.

**Comment by furilo** [comment]
In my case, whenever I go into a proposal, the Private Notes are opened, even if I collapsed it in the previous page view.

**Comment by furilo** [comment]
Proposal page with Private Notes block before Internal Evaluations
<img width="1438" alt="51545" src="https://github.com/AjuntamentdeBarcelona/decidim-internal-evaluation-module/assets/24740/2e53ef0e-7815-4412-ac59-73237bebed64">


Modal to edit
<img width="1436" alt="13091" src="https://github.com/AjuntamentdeBarcelona/decidim-internal-evaluation-module/assets/24740/38ccc557-e12b-43b9-a766-c3f5f00f67dc">

**Comment by furilo** [comment]
(take into account that currently Private Notes block will be opened by default)

**Comment by NilHomedes** [comment]
Thanks for the mock-up @furilo! Looks great. 
Just for the record, we have agreed that:
- Right now Private note are collpased by default, this should remain as it is (see how works in Nightly)
- Internal Status, will be open by default

**Comment by furilo** [comment]
> Right now Private note are collpased by default, this should remain as it
is (see how works in Nightly)

I don't know where the change of having Private Notes opened by default has
taken place. Just to confirm: it will be closed in any context, not just in
this module, right?

(having it closed when this module is activated while having it opened if
the module is not activated is possible, but it introduces extra complexity)

**Comment by NilHomedes** [comment]
> I don't know where the change of having Private Notes opened by default has taken place. Just to confirm: it will be closed in any context, not just in this module, right?

Yes, Private Notes will always be closed in any context. 
This behaviour might be introduced it here: https://github.com/decidim/decidim/pull/13017 I just left a comment to alert on this.

**Comment by entantoencuanto** [comment]
One question. General admins and participatory space admins can create private notes on proposals. Will they be able to create internal evaluations on proposals as well? If so I would create an evaluator role after creating the evaluation automatically to not break the counters of evaluators vs evaluations

**Comment by NilHomedes** [comment]
> One question. General admins and participatory space admins can create private notes on proposals. Will they be able to create internal evaluations on proposals as well?

No, only valuators assigned to a proposal will be able to create an internal evaluation on that proposal. If an admin is assigned as valuator, then they will be able to create an internal evaluation.

**Comment by furilo** [comment]
@NilHomedes is this the correct order? 

- Private notes
- Answer
- Internal evaluations

<img width="924" alt="71509" src="https://github.com/AjuntamentdeBarcelona/decidim-internal-evaluation-module/assets/24740/9f99e535-8f44-493b-9559-6d6171e57c00">

**Comment by NilHomedes** [comment]
@furilo The order should be:
- Private Notes
- Internal evaluations
- Answer

This order is following the logic order of these actions: First, you use Private notes to discuss or add extra information in a proposal. Second, you write your evaluation. And, finally, you answer publicly the proposal.

**Comment by Crashillo** [comment]
@NilHomedes could you please gimme push permission to this repo, please?

**Comment by NilHomedes** [comment]
> @NilHomedes could you please gimme push permission to this repo, please?

Done!

**Comment by Crashillo** [comment]
I cannot do push yet, is the user well-spelled?

```
hugo@ws:~/populate/decidim-internal-evaluation-module (internal-evaluations-creation)$ git push
ERROR: Permission to AjuntamentdeBarcelona/decidim-internal-evaluation-module.git denied to Crashillo.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```
