### ISSUE TITLE
Allow exporting internal evaluations

### ISSUE THREAD

**Issue by NilHomedes** [AjuntamentdeBarcelona/internal-evaluation-module#5]
**Is your feature request related to a problem? Please describe**
The internal evaluations are key to make a final decision on the answer to a proposal, so it’s necessary to have an easy way to export all the internal evaluations to work with it.

**Describe the solution you'd like**
I want a feature that allows me to export all the internal evaluations made in a proposals component.

The fields that would appear in the export file should be:

- Internal evaluation status
- Internal evaluation text
- Evaluator name
- Proposal Title
- Proposal Description

**Mockups**

**Does this issue could impact on users private data?**
No

**Acceptance Criteria:**

- [x] Given that I’m an administrator
When I click in the “Export all” button in the proposals list
Then I can see the option “Internal evaluations as csv/Json/Excel”
- [x] Given that I’m an administrator
When I click “Export all” and “Internal evaluations as csv”
Then I receive an email with the compressed csv file with all the internal evaluations
- [x] Given that I’m an administrator
When I click “Export all” and “Internal evaluations as excel”
Then I receive an email with the compressed excel file with all the internal evaluations
- [x] Given that I’m an administrator
When I click “Export all” and “Internal evaluations as json”
Then I receive an email with the compressed json file with all the internal evaluations
- [x] Given that I’m an administrator
When I receive an email with the compressed file with all the internal evaluations
Then I can download the file and see all the internal evaluations
The file comes with the fields: “Internal evaluation status”, “Internal evaluation text”, “Evaluator name”, “Proposal Title”, “Proposal Description”.

**Comment by mllocs** [comment]
@furilo ready to test in staging. 

When exporting, you'll receive the export by email, so, make sure that you have access to the logged user' email when exporting.

https://decidim-lot2.populate.tools/admin/participatory_processes/branch-highway/components/4/manage
