### ISSUE TITLE
Add in the export of internal evaluations all the evaluations including those that has not been done.

### ISSUE THREAD

**Issue by arnaumonty** [AjuntamentdeBarcelona/internal-evaluation-module#9]
Now it just exports the existing evaluations, but when we export we need to know which valuator has not done the evaluation. We want to see all the assigned valuators leaving empty fields of the internal evaluation if they have not done it.

At the same time, to facilitate the navigation, we need to add the scope and categories as new columns.

**Comment by mllocs** [comment]
@arnaumonty could you share an example of how that export would look like please?

**Comment by arnaumonty** [comment]
@mllocs Find attached screenshot about how it should look like in the xlsx file. The yellow ones would be the new ones.

![Screenshot from 2024-11-04 13-24-27](https://github.com/user-attachments/assets/92fa0d70-2975-426b-8289-e8952270ebf1)
